### ISSUE TITLE
Repeat button press

### ISSUE THREAD

**Issue by ArtlyStyles** [ros-drivers/joystick_drivers#139]
I am using the ROS joy package with Logictech game pad. I found that when I press the "A" button, it will trigger multiplie event in joy-call back. How can I prevent this an get only one call back? 

I noticed that the test program "jstest" trigger only one event when I press the "A" button.

**Comment by JWhitleyAStuff** [comment]
@ArtlyStyles - This is desired behavior. You should get one event for when the button is pressed (0->1 transition) and another when the button is released (1->0 transition). Otherwise, the receiving node would assume that the button was continually pressed until another button on the controller was pressed. Let me know if you have any additional questions or this is not the behavior you're seeing. Thanks.

**Comment by ArtlyStyles** [comment]
This is not the case, I usually got 3 events.

**Comment by JWhitleyAStuff** [comment]
What what's the difference between the contents of the three messages?

**Comment by ArtlyStyles** [comment]
with ros sensor_msg::Joy message, the button has only 0 or 1 state. My code is like this:

void MyClass::joyCallback(const sensor_msgs::Joy& msg)
{
     if (msg.buttons[0] == 1) {
         ROS_INFO("Button 0 pressed...");
    }
}

It printed the message 3 times when I pressed the button.

**Comment by JWhitleyAStuff** [comment]
Do you have the `autorepeat_rate` set to a value greater than 0.0? If so, it will continue to repeat the current button statuses every `coalesce_interval` seconds.

**Comment by ArtlyStyles** [comment]
Where do we set this?

**Comment by JWhitleyAStuff** [comment]
In the launch file or as a command-line argument when you launch the node. The official docs can be found here: http://docs.ros.org/api/joy/html/

**Comment by JWhitleyAStuff** [comment]
Closing for lack of response.
