### ISSUE TITLE
Detection of no spacemouse plugged in?

### ISSUE THREAD

**Issue by gedaliahknizhnik** [ros-drivers/joystick_drivers#254]
I'm using spacenav_node in ROS2 Foxy, and I'm noticing that there's no error generated if I start the node with no spacemouse plugged in. It just produces a stream of messages containing all zeros for the commands. Is this the intended behavior? Or is there an error handling bit that I'm missing?

**Comment by JWhitleyWork** [comment]
@gedaliahknizhnik Because the node is connecting to `spacenavd` which is always available whether a device is connected or not, this is currently intended behavior. However, this could be changed by attempting to poll some information about the device by using a function like `spnav_dev_name`. See https://spacenav.sourceforge.net/man_libspnav/#libspnav-api for more details. If you would like to open a PR to add this functionality, I would be happy to review it.
