### ISSUE TITLE
using the driver without graphic environment

### ISSUE THREAD

**Issue by camelator** [ros-drivers/joystick_drivers#279]
I am a little bit confused:

I am on Ubuntu 22.04 in command line.
just tried sudo apt install ros-humble-joy

"After this operation, 218 MB of additional disk space will be used." !!!!!
A joystick driver that take 218MB?
Reading installed packages (131 new packages!!!!) I can see for example it installs wayland packages, nouveau packages, mesa packages, radeon packages (!), pulse packages (!) libsndfiles (!) , ...

Well, do i need these packages working on SBC with command line? It is a lot of space,
is there any way to reduce the space taken ?

**Comment by JWhitleyWork** [comment]
@camelator The 218 MB is not for the driver, it is for the dependencies of the driver. This is because the `joy` package depends on SDL which is more of a multimedia framework. I recommend you download the repository from source and remove all folders except `joy_linux`, install the dependencies (from the base of your workspace) with the command below, then build only that package.

```
sudo apt update && rosdep install --from-paths src -i -y
```

**Comment by camelator** [comment]
it works far far better!

2 packages, 212 KB. Top solution, thanks
